language: elixir
elixir:
  - 1.7
otp_release:
  - 21.0
sudo: false
before_script:
  - mix deps.get
  - nvm install 6.2 && nvm use 6.2
  - mix format --check-formatted
  - mix compile --warnings-as-errors
script:
  - mix test
after_script:
  - mix coveralls.travis
cache:
  directories:
  - assets/node_modules